(() => {
  "use strict";
  const ADMIN_PASSWORD = "admin123";
  const KEY = "ballot_demo_state";
  const initialState = { election:{title:"Community Board Election",date:"2026-10-15",open:true}, candidates:[{id:"c1",name:"Maya Chen",description:"Focused on accessible community spaces and better local services.",image:"https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=600&q=80"},{id:"c2",name:"Daniel Brooks",description:"Focused on transparent budgets and practical neighborhood improvements.",image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80"}],voters:[],votes:[]};
  let state=loadState(), session=null, selectedCandidate=null, pendingAction=null;
  const $=(id)=>document.getElementById(id), authView=$("authView"), adminView=$("adminView"), voterView=$("voterView"), sessionBar=$("sessionBar");
  function loadState(){try{return Object.assign(structuredClone(initialState),JSON.parse(localStorage.getItem(KEY)||"{}"));}catch{return structuredClone(initialState);}}
  function saveState(){localStorage.setItem(KEY,JSON.stringify(state));}
  function showError(element,message){element.textContent=message;element.hidden=false;}
  function clearError(element){element.hidden=true;element.textContent="";}
  function esc(value){return String(value).replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));}
  document.querySelectorAll("[data-auth-tab]").forEach((tab)=>tab.addEventListener("click",()=>{document.querySelectorAll("[data-auth-tab]").forEach((item)=>item.classList.toggle("active",item===tab));$("loginForm").hidden=tab.dataset.authTab!=="login";$("registerForm").hidden=tab.dataset.authTab!=="register";}));
  $("loginForm").addEventListener("submit",(event)=>{event.preventDefault();clearError($("loginError"));const id=$("loginId").value.trim(),password=$("loginPassword").value;if(id.toLowerCase()==="admin"&&password===ADMIN_PASSWORD){session={role:"admin",label:"Administrator"};showApp();return;}const voter=state.voters.find((item)=>item.id.toLowerCase()===id.toLowerCase()&&item.password===password);if(!voter){showError($("loginError"),"Those details did not match an account.");return;}session={role:"voter",voterId:voter.id,label:voter.name};showApp();});
  $("registerForm").addEventListener("submit",(event)=>{event.preventDefault();clearError($("registerError"));const name=$("registerName").value.trim(),id=$("registerId").value.trim(),password=$("registerPassword").value;if(!name||!id||password.length<4){showError($("registerError"),"Add a name, voter ID card number, and a password of at least 4 characters.");return;}if(state.voters.some((voter)=>voter.id.toLowerCase()===id.toLowerCase())){showError($("registerError"),"That voter ID is already registered.");return;}state.voters.push({name,id,password,voted:false});saveState();$("registerForm").reset();document.querySelector('[data-auth-tab="login"]').click();showError($("loginError"),"Account created. You can sign in now.");$("loginError").className="success-message";});
  function showApp(){authView.hidden=true;adminView.hidden=session.role!=="admin";voterView.hidden=session.role!=="voter";sessionBar.hidden=false;$("sessionLabel").textContent=session.label;session.role==="admin"?renderAdmin():renderVoter();}
  $("logoutBtn").addEventListener("click",()=>{session=null;selectedCandidate=null;authView.hidden=false;adminView.hidden=true;voterView.hidden=true;sessionBar.hidden=true;});
  function renderAdmin(){ $("electionTitle").value=state.election.title;$("electionDate").value=state.election.date;$("adminStatus").textContent=state.election.open?"Voting open":"Voting ended";$("adminStatus").className=`status ${state.election.open?"open":"closed"}`;$("totalVotes").textContent=state.votes.length;$("registeredCount").textContent=state.voters.length;renderAdminCandidates();renderResults();const counts=getCounts(),max=Math.max(...Object.values(counts),0),leader=state.candidates.find((candidate)=>counts[candidate.id]===max&&max>0);$("winnerName").textContent=leader?leader.name:"No votes yet";$("winnerVotes").textContent=leader?`${counts[leader.id]} vote${counts[leader.id]===1?"":"s"} so far`:"The result will calculate automatically."; }
  function renderAdminCandidates(){ $("adminCandidateList").innerHTML=state.candidates.map((candidate)=>`<article class="candidate-admin"><img src="${esc(candidate.image)}" alt="${esc(candidate.name)}"><div class="candidate-admin-body"><input data-candidate-name="${candidate.id}" value="${esc(candidate.name)}" aria-label="Candidate name"><textarea data-candidate-description="${candidate.id}" rows="2" aria-label="Candidate description">${esc(candidate.description)}</textarea><div class="candidate-tools"><button class="icon-button" data-save-candidate="${candidate.id}" type="button">Save</button><button class="icon-button" data-remove-candidate="${candidate.id}" type="button">Remove</button></div></div></article>`).join(""); }
  function getCounts(){return state.candidates.reduce((counts,candidate)=>{counts[candidate.id]=state.votes.filter((vote)=>vote===candidate.id).length;return counts;},{});}
  function renderResults(){const counts=getCounts(),total=state.votes.length;$("adminResults").innerHTML=state.candidates.map((candidate)=>{const count=counts[candidate.id],percent=total?Math.round(count/total*100):0;return `<div class="result-row"><div class="result-top"><span class="result-name">${esc(candidate.name)}</span><span class="result-stats">${count} vote${count===1?"":"s"} · ${percent}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${percent}%"></div></div></div>`;}).join("");}
  $("settingsForm").addEventListener("submit",(event)=>{event.preventDefault();state.election.title=$("electionTitle").value.trim()||initialState.election.title;state.election.date=$("electionDate").value;saveState();$("settingsMessage").textContent="Settings saved.";$("settingsMessage").hidden=false;renderAdmin();});
  $("adminCandidateList").addEventListener("click",(event)=>{const saveId=event.target.dataset.saveCandidate,removeId=event.target.dataset.removeCandidate;if(saveId){const candidate=state.candidates.find((item)=>item.id===saveId);candidate.name=document.querySelector(`[data-candidate-name="${saveId}"]`).value.trim()||candidate.name;candidate.description=document.querySelector(`[data-candidate-description="${saveId}"]`).value.trim();saveState();renderAdmin();}if(removeId&&state.candidates.length>1){state.candidates=state.candidates.filter((candidate)=>candidate.id!==removeId);state.votes=state.votes.filter((vote)=>vote!==removeId);saveState();renderAdmin();}});
  $("addCandidateBtn").addEventListener("click",()=>{const name=prompt("Candidate name");if(!name||!name.trim())return;state.candidates.push({id:`c${Date.now()}`,name:name.trim(),description:"Add a short candidate statement.",image:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80"});saveState();renderAdmin();});
  function renderVoter(){const voter=state.voters.find((item)=>item.id===session.voterId);$("voterElectionTitle").textContent=state.election.title;$("voterElectionDate").textContent=state.election.date?`Closes ${new Date(`${state.election.date}T12:00:00`).toLocaleDateString(undefined,{month:"long",day:"numeric",year:"numeric"})}`:"No closing date set";$("voterStatus").textContent=state.election.open?"Voting open":"Voting ended";$("voterStatus").className=`status ${state.election.open?"open":"closed"}`;$("voterCandidateList").innerHTML=state.candidates.map((candidate)=>`<article class="candidate-voter ${selectedCandidate===candidate.id?"selected":""}" data-voter-candidate="${candidate.id}"><img src="${esc(candidate.image)}" alt="${esc(candidate.name)}"><div class="candidate-voter-body"><h2>${esc(candidate.name)}</h2><p>${esc(candidate.description)}</p><label class="select-row"><input type="radio" name="candidate" ${selectedCandidate===candidate.id?"checked":""} ${voter?.voted||!state.election.open?"disabled":""}> Select candidate</label></div></article>`).join("");$("castVoteBtn").hidden=Boolean(voter?.voted||!state.election.open);$("votedMessage").hidden=!voter?.voted;$("endVotingBtn").disabled=!state.election.open;}
  $("voterCandidateList").addEventListener("click",(event)=>{const card=event.target.closest("[data-voter-candidate]");if(!card||!state.election.open)return;selectedCandidate=card.dataset.voterCandidate;renderVoter();});
  $("castVoteBtn").addEventListener("click",()=>{clearError($("voterMessage"));const voter=state.voters.find((item)=>item.id===session.voterId);if(!selectedCandidate){showError($("voterMessage"),"Select a candidate first.");return;}if(!voter||voter.voted||!state.election.open)return;state.votes.push(selectedCandidate);voter.voted=true;saveState();renderVoter();});
  function openModal(){pendingAction="end";$("modalPassword").value="";clearError($("modalError"));$("passwordModal").hidden=false;$("modalPassword").focus();}
  $("endVotingBtn").addEventListener("click",openModal);$("passwordModal").addEventListener("click",(event)=>{if(event.target.dataset.closeModal!==undefined||event.target===$("passwordModal"))$("passwordModal").hidden=true;});$("modalConfirm").addEventListener("click",()=>{if($("modalPassword").value!==ADMIN_PASSWORD){showError($("modalError"),"Incorrect administrator password.");return;}if(pendingAction==="end"){state.election.open=false;saveState();$("passwordModal").hidden=true;renderVoter();}});$("modalPassword").addEventListener("keydown",(event)=>{if(event.key==="Enter")$("modalConfirm").click();});
})();